name: yaml2dart
description: Converts a YAML file to a Dart file containing global scope constants. Especially good for pubspec.yaml.
version: 1.5.1
repository: https://github.com/insign/dart_yaml2dart

environment:
  sdk: '>=3.6.2 <4.0.0'

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.26.3

dependencies:
  recase: ^4.1.0
  yaml: ^3.1.3
