name: yaml2dart
description: Converts a YAML file to a Dart file containing global scope constants. Especially good for pubspec.yaml.
version: 1.3.0
repository: https://github.com/insign/dart_yaml2dart

environment:
  sdk: ">=2.19.2 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  path: ^1.8.3
  test: ^1.21.0

dependencies:
  recase: ^4.1.0
  yaml: ^3.1.1
