import 'dart:io';
import 'package:yaml/yaml.dart';
import 'package:recase/recase.dart';

/// A utility class for converting YAML files to Dart constants.
class Yaml2Dart {
  final String inputFilePath;
  final String outputFilePath;
  final String warning = '// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.';

  /// Creates a new instance of the `Yaml2Dart` class.
  ///
  /// [inputFilePath] is the path to the input YAML file.
  /// [outputFilePath] is the path to the output Dart file.
  Yaml2Dart(this.inputFilePath, this.outputFilePath);

  /// Converts the input YAML file to a Dart file containing constants.
  Future<void> convert() async {
    // Read the YAML file.
    final file = File(inputFilePath);
    final contents = await file.readAsString();
    final yaml = loadYaml(contents);

    // Create the output Dart file.
    final output = File(outputFilePath);
    final buffer = StringBuffer();

    buffer.writeln(warning);

    // Write each key-value pair in the YAML file as a Dart constant.
    yaml.forEach((key, value) {
      key = ReCase(key).camelCase;
      buffer.writeln('const $key = ${_toDartCode(value)};');
    });

    // Write the contents to the output file.
    await output.writeAsString(buffer.toString());
  }

  String _toDartCode(dynamic value) {
    if (value is String) {
      return "'${value.replaceAll("'", "\\'")}'";
    } else if (value is num || value is bool) {
      return value.toString();
    } else if (value is List) {
      final elements = value.map((e) => _toDartCode(e)).join(', ');
      return 'const [$elements]';
    } else if (value is Map) {
      final entries = value.entries
          .map((e) => "'${e.key}': ${_toDartCode(e.value)}")
          .join(', ');
      return 'const {$entries}';
    } else {
      return "'$value'";
    }
  }
}
