import 'dart:convert';
import 'dart:io';
import 'package:yaml/yaml.dart';
import 'package:recase/recase.dart';

/// A utility class for converting YAML files to Dart constants.
class Yaml2Dart {
  final String inputFilePath;
  final String outputFilePath;
  final String warning =
      '// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.';

  /// Creates a new instance of the `Yaml2Dart` class.
  ///
  /// [inputFilePath] is the path to the input YAML file.
  /// [outputFilePath] is the path to the output Dart file.
  Yaml2Dart(this.inputFilePath, this.outputFilePath);

  dynamic _convertNode(dynamic node) {
    if (node is YamlMap) {
      return node.map(
        (key, value) => MapEntry(key.toString(), _convertNode(value)),
      );
    }
    if (node is YamlList) {
      return node.map(_convertNode).toList();
    }
    return node;
  }

  String _formatValue(dynamic value) {
    if (value is String) {
      final encoded = jsonEncode(value);
      final escaped = encoded
          .substring(1, encoded.length - 1)
          .replaceAll("'", r"\'")
          .replaceAll(r'$', r'\$');
      return "'$escaped'";
    }
    if (value is num || value is bool) {
      return value.toString();
    }
    if (value == null) {
      return 'null';
    }

    final plainObject = _convertNode(value);
    return jsonEncode(plainObject).replaceAll(r'$', r'\$');
  }

  /// Converts the input YAML file to a Dart file containing constants.
  Future<void> convert() async {
    // Read the YAML file.
    final file = File(inputFilePath);
    final contents = await file.readAsString();
    final yaml = loadYaml(contents);

    // Create the output Dart file.
    final output = File(outputFilePath);
    final buffer = StringBuffer();

    buffer.writeln(warning);

    if (yaml is YamlMap) {
      yaml.forEach((key, value) {
        final keyString = ReCase(key.toString()).camelCase;
        buffer.writeln('const $keyString = ${_formatValue(value)};');
      });
    }

    // Write the contents to the output file.
    await output.writeAsString(buffer.toString());
  }
}
